spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
#  server:
#    eviction-interval-timer-in-ms: 30000
  client:
    eureka-server-connect-timeout-seconds: 10
    enabled: true
    register-with-eureka: false
