server:
  port: 5100

spring:
  application:
    name: auth-server

eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761
    register-with-eureka: true
    healthcheck:
      enabled: true


management:
  endpoints:
    enabled-by-default: on
    web:
      exposure:
        include: health,info,prometheus,metrics,env,threaddump,loggers,configprops

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: on

  metrics:
    export:
      prometheus:
        enabled: on
      jmx:
        enabled: on
        domain: ${spring.application.name}
