server:
  port: 5100

application:
  user-encryption:
    password-salt: 20211029
    iterations: 200000
    hash-width: 512
  token-encryption:
    scope-claim-name: authority
    expiry-minutes: 60
    sign-token-key-path: /Users/dipeshm/workspace/external_source/keys/token-private.p8

spring:
  application:
    name: auth-server

eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    service-url:
      default-zone: http://localhost:8761
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    enabled-by-default: on
    web:
      exposure:
        include: health,info,prometheus,metrics,env,threaddump,loggers,configprops

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: on

  metrics:
    export:
      prometheus:
        enabled: on
      jmx:
        enabled: on
        domain: ${spring.application.name}
