server:
  port: 5100

spring:
  application:
    name: auth-server

eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    service-url:
      default-zone: http://localhost:8761
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    enabled-by-default: on
    web:
      exposure:
        include: health,info,prometheus,metrics,env,threaddump,loggers,configprops

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: on

  metrics:
    export:
      prometheus:
        enabled: on
      jmx:
        enabled: on
        domain: ${spring.application.name}
