server:
  port: 5000

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      enabled: true

    gateway:
      routes:
      - id: auth-route
        uri: lb://auth-server/
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<segment>.*), /$\{segment}



#        - name: Hystrix
#          args:
#            fallbackUri: forward:/fallback

eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    service-url:
      default-zone: http://localhost:8761
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    enabled-by-default: on
    web:
      exposure:
        include: health,info,prometheus,metrics,env,threaddump,loggers,configprops,hystrix.stream

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: on

  metrics:
    export:
      prometheus:
        enabled: on
      jmx:
        enabled: on
        domain: ${spring.application.name}
